### ISSUE TITLE
Why handling stdin and args differently

### ISSUE THREAD

**Issue by casimir** [getantibody/antibody#11]
Just an idea but why not treat several arguments to `bundle` the same way than `stdin`?
If you think about it you already have the code, having [this function](https://github.com/caarlos0/antibody/blob/master/api.go#L20) taking the bundle list as argument instead of a file reader would do the trick. This way you could have concurrent loading directly from your `.zshrc`:
```
antibody bundle name1 name2 name3 name4

# Or maybe more readable

antibody bundle name1 \
                name2 \
                name3 \
                name4
```
Or maybe I'm completely wrong but let me know too. :wink:

**Comment by caarlos0** [comment]
Good idea, @casimir!

I'm doing some refectories now, when I finish, I'll do this!

Many thanks!

**Comment by caarlos0** [comment]
I decided not to do that, because if I do, I would not be able to lock versions of stuff, or add other params in the future...
