### ISSUE TITLE
Request of next release

### ISSUE THREAD

**Issue by wkentaro** [getantibody/antibody#110]
Could anyone please work for this?

I need this commit: https://github.com/getantibody/antibody/commit/9a027f85ea8108b2b2c9540630903798d01821b1

**Comment by caarlos0** [comment]
yes, will do it right away... I totally forgot to create the tag :/

**Comment by caarlos0** [comment]
Done: https://github.com/getantibody/antibody/releases/tag/v0.7.1

**Comment by wkentaro** [comment]
Thanks!
