### ISSUE TITLE
Compiling source

### ISSUE THREAD

**Issue by combro2k** [getantibody/antibody#114]
Hi there,

I was trying to compile the source by hand;
Found out the executable where complaining about:

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  
This is an error in the application. 
Please contact the distributor of this application if this is not you.  
```
See [https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature](https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature)

You can fix that by changing the cmd/antibody/command/*.go files where (ctx *cli.Context) is to change it for example to:

```
func doBundle(ctx *cli.Context) error {
	if readFromStdin() {
		entries, _ := ioutil.ReadAll(os.Stdin)
		antibody.New(
			bundle.Parse(string(entries), antibody.Home()),
		).Download()
	} else {
		antibody.New(
			[]bundle.Bundle{bundle.New(ctx.Args().First(), antibody.Home())},
		).Download()
	}

	return nil;
}
```

The type error interface need to be added there and it has to have a return.. 
Or maybe I did something wrong here and you dont get that message ;-)

**Comment by caarlos0** [comment]
@combro2k probably the version we are using don't have this change yet.

Either way, I'll update the deps and fix this issue.

For now, you can use Glide to manage the deps. Check `.travis.yml` for details 👍

**Comment by caarlos0** [comment]
Oh, and thanks for reporting the issue :D

**Comment by caarlos0** [comment]
@combro2k should be good now 👍
