### ISSUE TITLE
Add fish support

### ISSUE THREAD

**Issue by caarlos0** [getantibody/antibody#133]
Yeah, this is happening

**Comment by hhsnopek** [comment]
🐟 🐟 🐟 🐠

**Comment by hhsnopek** [comment]
If you could give me a lead on this, I can PR this baby in

**Comment by caarlos0** [comment]
@hhsnopek Sure 🎆

**Comment by caarlos0** [comment]
is this still desired?

**Comment by hhsnopek** [comment]
not anymore, I moved away from fish a while back. Sorry for the lack of a follow up!

**Comment by caarlos0** [comment]
np :)
