### ISSUE TITLE
How can I use themes from oh-my-zsh repo?

### ISSUE THREAD

**Issue by yevhen-m** [getantibody/antibody#152]
I want to use a theme, that lives in robbyrussell/oh-my-zsh repo. How can I use it?

**Comment by caarlos0** [comment]
Hi @yevhen-m,

Themes inside the main oh-my-zsh repo wont work, as described in [readme](https://github.com/getantibody/antibody#what-doesnt-work).

Any theme that has it's own repo is expected to work though.

**Comment by a7madgamal** [comment]
can we atleast keep this open for someone to fix oneday? It's not fixed I guess :(

**Comment by BirkhoffLee** [comment]
+1 for @a7madgamal

**Comment by BirkhoffLee** [comment]
It won't.

If I use `robbyrussell/oh-my-zsh path:themes/avit.zsh-theme`, it won't work cause of permission denied. Maybe I missed something?

**Comment by ayanul** [comment]
robbyrussell/oh-my-zsh path:lib
robbyrussell/oh-my-zsh path:themes/robbyrussell.zsh-theme

**Comment by zakkak** [comment]
I believe that this should be mentioned in the documentation. @caarlos0 what do you think? Would you merge a PR documenting how to use ohmyzsh themes with `path:`?

**Comment by caarlos0** [comment]
hey @zakkak yeah that would be nice, maybe a section called "using with oh-my-zsh" or something

if you can open a PR that would be awesome, thanks!
