### ISSUE TITLE
/tmp/antibody-log causes problems with multiple antibody users on the same system

### ISSUE THREAD

**Issue by mknaf** [getantibody/antibody#158]
On several occasions, `antibody` writes to `/tmp/antibody-log`. If you have multiple users on the same system using `antibody`, all but the user who created `/tmp/antibody-log` first will be denied write permissions, causing `zsh` to start without any plugins loaded.

**Comment by caarlos0** [comment]
There is nothing writing to this file in recent versions.

What version of antibody are you using?

**Comment by mknaf** [comment]
Oh, my apologies. I was installing antibody via a home-folder setup script which has the version hard coded. To 0.4.0, unfortunately. Sorry again.

**Comment by caarlos0** [comment]
No problem =)
