### ISSUE TITLE
Howto add a local bundle?

### ISSUE THREAD

**Issue by dritter** [getantibody/antibody#160]
Hi there!

I've been trying to setup antibody with a local bundle. I couldn't find any word about this in the README, only in #103 there are a few notes about bundle name starting with a slash. But if I do `antibody bundle /my/local/thingy`, it wouldn't work.

I am using antibody 2.2.0

Help appreciated ;)
Thanks

**Comment by caarlos0** [comment]
Hi @dritter, it should work that way.

![image](https://cloud.githubusercontent.com/assets/245435/21532570/8d117cce-cd38-11e6-8d46-3fbebc745446.png)

Are you sure the path you provided is valid? Does it have a `.zsh` file or something?

**Comment by dritter** [comment]
So, having to source the bundle is the "static loading" strategy, right?
Let's pretend I want to load `zsh-users/zsh-completions` from disk, then I have to write
```zsh
antibody bundle /my/path/zsh-completions
source /my/path/zsh-completions/zsh-completions.plugin.zsh
```
But if I load it from github, all I have to write is
```zsh
antibody bundle zsh-users/zsh-completions
```

To be more specific, I am writing a ZSH theme and want it to test it with various plugin managers in a VM. That is why I want antibody to load the theme from disk the way antibody does it (I know that sourcing the theme works)..
