### ISSUE TITLE
A "clean" method to delete plugins unused?

### ISSUE THREAD

**Issue by simonbcn** [getantibody/antibody#162]
It would be very useful a command similar to `clean` of https://github.com/zplug/zplug#2-commands-for-zplug to remove repositories which are no longer managed/used.

**Comment by caarlos0** [comment]
Since we don't maintain a list of used plugins, I don't see how this can be done...

The easier way is to `rm -rf $(antibody home)` and then load all used plugins again.

**Comment by simonbcn** [comment]
Antibody knows the loaded plugins and it knows the plugins in local folder. It's obvious that it knows that plugins aren't loaded.

**Comment by caarlos0** [comment]
No, it doesn't know.

It only knows what you pass to it on the spot. For example:

```sh
antibody bundle a/b # antibody knows only about a/b
antibody bundle a/d # antibody knows only about a/d
antibody clean # at this point, antibody knows nothing about what is loaded, only that a/b and a/d were downloaded one day...
```

The only way would be if we look into the current `PATH` and loaded functions, but I think it's overkill.

Sorry, but IMHO this is a wontfix.

Thanks for using antibody 🍻

**Comment by simonbcn** [comment]
I completely disagree. I quote:
> Antibody does just those three things, but you don't even need to apply. Running `antibody bundle` will already **download and apply** the given bundle.

> `antibody list` list all currently downloaded bundles.

When antibody executes `bundle`, it loads those bundles and when it executes `clean`, it knows what plugins are loaded. It's as simple as comparing plugins loaded into memory and those on the disk. 
I don't think it's a crazy idea or difficult to implement.


`zplug`, `antigen`, etc... All of them have a method that allows to keep the local repository clean easily.

**Comment by caarlos0** [comment]
Antibody doesn't have a list of used/unused bundles, it just have the folder with the bundles that someday the user bundled. 

What apply means:

- https://github.com/getantibody/antibody/blob/master/bundle/path.go#L13
- https://github.com/getantibody/antibody/blob/master/bundle/zsh.go#L25

My concept of knowing would be to maintain some kind of list of what is currently being used or not, which antibody doesn't have, but maybe your concept is different.

Anyway, if you think you it's doable, feel free to open a PR.
