### ISSUE TITLE
Installation script provided in README does not work

### ISSUE THREAD

**Issue by GohNicho** [getantibody/antibody#173]
When I use the provided script from the `README` it doesn't install correctly. Error message seems to indicate that it might be a formatting/syntax error 

![image](https://cloud.githubusercontent.com/assets/5589658/23827982/46402ed0-0690-11e7-968d-146c8540f922.png)

**Comment by caarlos0** [comment]
@GohNicho fixed on v2.3.6 :)

Thanks for the report!
