### ISSUE TITLE
Equivalent of `antibody purge`?

### ISSUE THREAD

**Issue by ollien** [getantibody/antibody#182]
I've been checking this out and the one feature I really think is missing is the equivalent of `antigen purge.` The only way I can see to remove plugins is to just rm them from ANTIBODY_HOME, which doesn't feel like something I should have to do with a plugin manager. Is there a better way to do this or does antibody not have support for it?

**Comment by caarlos0** [comment]
I guess we can add it, yes..

**Comment by caarlos0** [comment]
#183 :)

**Comment by ollien** [comment]
What a turnaround time! Thanks!
