### ISSUE TITLE
Missing release for Darwin x86_64

### ISSUE THREAD

**Issue by twang-rs** [getantibody/antibody#184]
```
curl -sL https://git.io/antibody | bash -s
```

This attempts to fetch the URL: `https://github.com/getantibody/antibody/releases/download/v3.1.1/antibody_Darwin_x86_64.tar.gz`

The releases page for v3.1.1 does not include artifact:

antibody_Darwin_x86_64.tar.gz

Instead it has:

antibody_3.1.1_darwin_amd64.tar.gz

**Comment by caarlos0** [comment]
should be good now, thanks for reporting!

**Comment by twang-rs** [comment]
Negative.  The artifacts still show as:

antibody_darwin_amd64.tar.gz

```
echo $(uname -s) => Darwin
echo $(uname -m) => x86_64
```

So, the release file it tries to download is:

antibody_Darwin_x86_64.tar.gz

**Comment by caarlos0** [comment]
Woops, lemme check

**Comment by caarlos0** [comment]
```
❯ curl -sL https://git.io/antibody | bash -s
Downloading antibody v3.1.3 for Darwin_x86_64...
Password:

```

now it's good =)
