### ISSUE TITLE
antibody branch:<branch> doesn't seem to work

### ISSUE THREAD

**Issue by danihodovic** [getantibody/antibody#185]
I'm trying to use a theme on the `dev` branch. The example below doesn't seem to be working. I took the example from README.md: 

> You can also specify a branch to download, for example, antibody bundle caarlos0/jvm branch:v2 will download the v2 branch of that repository.

```
antibody bundle danihodovic/mostar.zsh branch:dev
```

**Comment by caarlos0** [comment]
@danihodovic probably you ran `antibody bundle danihodovic/mostar.zsh` and then tried `antibody bundle danihodovic/mostar.zsh`?

I tested it here, and it works:

```console
~
❯ antibody bundle danihodovic/mostar.zsh branch:dev
source /Users/carlos/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-danihodovic-SLASH-mostar.zsh/mostar.zsh-theme

~ 2s
❯ cd /Users/carlos/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-danihodovic-SLASH-mostar.zsh

~/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-danihodovic-SLASH-mostar.zsh dev
❯ git branch
* dev
```

try `rm -rf  $(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-danihodovic-SLASH-mostar.zsh` and then run `antibody bundle danihodovic/mostar.zsh branch:dev`, it should work.

**Comment by danihodovic** [comment]
It worked after removing the theme directory.
```
rm -rf .cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-danihodovic-SLASH-mostar.zsh

$ antibody bundle danihodovic/mostar.zsh branch:dev

$ pwd
/home/dani/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-danihodovic-SLASH-mostar.zsh

$ git branch
* master
```

Thanks!
