### ISSUE TITLE
`antibody bundle` just asks for GitHub username and hangs

### ISSUE THREAD

**Issue by laurenkt** [getantibody/antibody#190]
When trying to use antibody to install a plugin from [a particular repo](https://github.com/guildencrantz/vi-mode-cursor.plugin.zsh), antibody just displays:

```
Username for 'https://github.com':
```
and hangs permanently – ignoring any username or any other input, including ^C and ^Z.

Looking at the particular repo, https://github.com/guildencrantz/vi-mode-cursor.plugin.zsh, doesn't seem to show anything unusual, so it seems like an antibody issue. Any ideas?

<img width="539" alt="screen shot 2017-09-08 at 21 12 03" src="https://user-images.githubusercontent.com/1607874/30229571-653dbf40-94da-11e7-8286-41db31412a20.png">

**Comment by laurenkt** [comment]
I figured out the issue here: the repo didn't exist (I was missing the .plugin.zsh from the end). Because it couldn't find a public repo I think GitHub asks for authentication in case it's a private repo.

I can reproduce with, e.g.

```
antibody bundle abcd/efg
```

I think however that hanging and eating ^C and ^Z to no effect is probably still undesirable behaviour. What are your thoughts?

**Comment by caarlos0** [comment]
Hi @laurenkt ,

Can you try `antibody bundle git@github.com:user/repo.git` please?

Since it's a private repo, the default HTTPS URL will indeed not work...

**Comment by laurenkt** [comment]
It's not a private repo – it was a misspelled repo. The problem is that it hangs on the terminal and ignores ^C/^Z until you `kill -9` it from another session.

**Comment by caarlos0** [comment]
oh, yeah, that surely can be improved...

thanks for the report =D

**Comment by caarlos0** [comment]
v3.2.2 should have this fixed, thanks :D
