### ISSUE TITLE
Limit the number of installations in parallel

### ISSUE THREAD

**Issue by thiagotalma** [getantibody/antibody#194]
Hello Carlos. Congratulations on the excellent work.

The possibility of installing all bundles in parallel is very good. But there is a problem when the machine has a resource limitation.

For example, I am using a virtual machine to test your dotfiles and it is impossible to end the bootstrap with more than 10 plugins. All VM resources are consumed by the various instances of git and it hangs.

Is it possible to limit the number of installations running in parallel?

Thanks!

**Comment by caarlos0** [comment]
Hi @thiagotalma, yes, I think it's doable!

Will try to add this today.

Thanks for reporting it BTW!

**Comment by thiagotalma** [comment]
Show Carlos. Valeu!

**Comment by thiagotalma** [comment]
@caarlos0 não sei se eu fiz algo de errado, mas aparentemente não mudou o processo, veja o print.
Há alguma coisa a mais que eu preciso fazer?

![](https://i.imgur.com/jUp1yYj.png)

**Comment by caarlos0** [comment]
tu rodou update, no update nao tá usando o parallelism, vou corrigir

**Comment by caarlos0** [comment]
v3.3.1 should fix this

**Comment by thiagotalma** [comment]
Thanks! Works like a charm.
