### ISSUE TITLE
antibody bundle < $HOME/.zsh-plugins > static-plugins.zsh

### ISSUE THREAD

**Issue by mtxr** [getantibody/antibody#207]
I tried to use static loading as Readme.md suggests but the following command generates an empty file.

`antibody bundle < $HOME/.zsh-plugins > static-plugins.zsh`

`$HOME/.zsh-plugins`was generated using `echo 'plugin-author/plugin-name' > $HOME/.zsh-plugins` and it's working if used like `antibody bundle < $HOME/.zsh-plugins`.

Am I doing it wrong?

**Comment by caarlos0** [comment]
it should work I guess:

```console
/tmp
λ echo 'caarlos0/jvm' > zsh-plugins

/tmp
λ which antibody
/usr/local/bin/antibody

/tmp
λ antibody -v
antibody version 3.4.1

/tmp
λ antibody bundle < zsh-plugins > static-plugins

/tmp
λ cat static-plugins
source /Users/carlos/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-caarlos0-SLASH-jvm/jvm.plugin.zsh

/tmp
λ

```

**Comment by caarlos0** [comment]
Oh, I see what happened. You did `antibody init`, right? You have to choose between doing the `init` or using it to generate the static plugins file.

Either way this can probably be improved..

**Comment by mtxr** [comment]
You were completely right!

I don't think you need to change any code, but update the docs would be really great.

Thank you @caarlos0

**Comment by caarlos0** [comment]
docs: https://github.com/getantibody/antibody/commit/c0055235e31597fada459397d42d6b27127c8a52
