### ISSUE TITLE
How can I install enhancd with antibody?

### ISSUE THREAD

**Issue by nikitavoloboev** [getantibody/antibody#213]
I am trying to install [enhancd](https://github.com/b4b4r07/enhancd) but I am not sure how I can use it with antibody.

I tried doing this but it fails:

![2017-12-30 at 18 18](https://user-images.githubusercontent.com/6391776/34456057-e4e842e0-ed8d-11e7-902b-a53a763c8522.png)

This is the file found [here](https://github.com/nikitavoloboev/dotfiles/tree/master/antibody).

Thank you for any help.

**Comment by caarlos0** [comment]
yeah, this is not a valid antibody syntax

you can put just the repo, like this:

```
b4b4r07/enhancd
```

seems like it would work:

```console
$ antibody bundle 'b4b4r07/enhancd'
source /Users/carlos/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-b4b4r07-SLASH-enhancd/init.sh
```
