### ISSUE TITLE
How to install nix-zsh-completions with Antibody if I can

### ISSUE THREAD

**Issue by nikitavoloboev** [getantibody/antibody#215]
I want to install [nix-zsh-completions](https://github.com/spwhitt/nix-zsh-completions) so I tried add it to my `plugins.txt` file like so:

![2018-01-27 at 01 01](https://user-images.githubusercontent.com/6391776/35465626-b16de3fe-02fd-11e8-9d98-675bb34261b1.png)

However this errors out and gives:
```Bash
2018/01/27 01:02:24 git clone failed for https://github.com/nix-zsh-completions
```

Is it possible to install this completions with Antibody?

Thank you for any help.

**Comment by caarlos0** [comment]
hi @nikitavoloboev 

can you try `spwhitt/nix-zsh-completions` instead?

**Comment by nikitavoloboev** [comment]
Oh wow. Silly me, I thought I included the username for some reason. 

This works well. 🎊

**Comment by caarlos0** [comment]
no problem, glad it worked out =D
