### ISSUE TITLE
Is it possible to load a certain branch when loading a plugin?

### ISSUE THREAD

**Issue by nikitavoloboev** [getantibody/antibody#216]
I hit [this issue](https://github.com/zsh-users/zsh-autosuggestions/issues/307) with one of the plugins I use. 

The solution to the issue lies in a `develop` branch of the repo and author is nor merging it to master. 

Is it possible to load this plugin and specify which branch to clone?

**Comment by caarlos0** [comment]
@nikitavoloboev http://getantibody.github.io/#options.branch this should work

**Comment by nikitavoloboev** [comment]
Thank you @caarlos0 

This worked.
