### ISSUE TITLE
Support for completion scripts?

### ISSUE THREAD

**Issue by okuuva** [getantibody/antibody#217]
I recently switched from oh-my-zsh to antibody and gotta say, I'm impressed. One thing I found odd was that some of the oh-my-zsh plugins, namely docker and vagrant, seized to work even though other plugins worked just fine. After some investigation, I came to conclusion that the reason is that those plugins only contain some autocompletion scripts name _<plugin> with no .zsh scripts in them, so bundle doesn't collect them. I was wondering if there's any plan on supporting completion scritps such as docker script linked below?

https://github.com/docker/cli/tree/master/contrib/completion/zsh

**Comment by caarlos0** [comment]
hmm, didn't know people use antibody for that use case (I for instance just add the `source file` to my zshrc), but I think this can be done with a `file:path` "annotation" into the antibody syntax...

what do you think

**Comment by okuuva** [comment]
Well, I'd prefer to be able to use one plugin manager for everything, i.e. not have to be able to manually fetch and source completion scripts but add them to zsh plugins file instead.

I tried adding the following line to my .zsh_plugins:
`robbyrussell/oh-my-zsh folder:plugins/docker kind:path`
But it doesn't seem to work. Well, it does in a sense that the directory is added to my $PATH but having it there doesn't source it automatically and adding `source _docker` does not seem to have any effect.

Note that oh-my-zsh docker plugin is just a copy of the official docker zsh completion script, so I'm using it here as omz is already cached by antibody as I'm using other plugins from there as well.

**Comment by caarlos0** [comment]
@okuuva check #220

**Comment by okuuva** [comment]
Hi @caarlos0 !

So sorry about long, long radio silence, I simply forgot about this one! #220 seems exactly what I was thinking about, could you be so kind to give short instructions on how to build antibody from a certain branch? I've always just used the shell script from getantibody.github.io...

**Comment by caarlos0** [comment]
I'll release a new version with the fix :)

**Comment by zx1986** [comment]
@caarlos0  Hello, did you get this work?

here is my config:

```
antibody bundle gantsign/zsh-plugins path:ctop
antibody bundle gantsign/zsh-plugins path:bat
antibody bundle docker/cli path:contrib/completion/zsh/_docker
antibody bundle denysdovhan/spaceship-prompt
```

```
antibody bundle gantsign/zsh-plugins path:ctop
antibody bundle gantsign/zsh-plugins path:bat
antibody bundle docker/cli path:contrib/completion/zsh/_docker
antibody bundle denysdovhan/spaceship-prompt
```

both not working :-(

refs: https://getantibody.github.io/options/
