### ISSUE TITLE
[Suggestion] Add instructions on how to properly use oh-my-zsh (not its plugins)

### ISSUE THREAD

**Issue by GUiHKX** [getantibody/antibody#218]
Hello!

I just migrated from antigen to antibody, and it's way faster, so thank you for that. However, I wasn't able to use oh-my-zsh properly. I'm not talking about using its plugins, but oh-my-zsh itself. I'm referring to tweaks that are applied when you call `antigen use oh-my-zsh`. Or when running antibody: `antibody bundle robbyrussell/oh-my-zsh`.

But that doesn't work for antibody unless we add a workaround. To demonstrate this, let's assume we have `robbyrussell/oh-my-zsh` in our `~/.zsh_plugins.txt`. We'll always get two error messages after launching our terminal:

```
zsh: can't open input file: /tools/check_for_upgrade.sh
/home/user/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/oh-my-zsh.sh:31: no matches found: /lib/*.zsh
```

The first thing to do is disable update checking, because antibody can do that for us already. So we add the following line to our  `~/.zshrc`:

```
DISABLE_AUTO_UPDATE=true
```

The first error message is gone. Now for the second one, we must set a variable named `ZSH` and its value being the path of our oh-my-zsh installation. "But why?". Because [oh-my-zsh's init plugin](https://github.com/robbyrussell/oh-my-zsh/blob/a1d13aa0b4a794c4f10fdd9d69d59ce2d04c3785/oh-my-zsh.sh#L3) needs this variable set, in order to run properly. Antigen has a [helper script](https://github.com/zsh-users/antigen/blob/09e589f69d489dccd9ebf1c1a66831a6e3d818c9/src/lib/use-oh-my-zsh.zsh#L5) that automatically sets this `ZSH` variable when we run `antigen use robbyrussell/oh-my-zsh`.

So to finally fix that error on antibody, we also add the following line to our `~/.zshrc`:

```zsh
ZSH="${HOME}/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
```

And that's pretty much it it! 

**P.S.:** All scripts that oh-my-zsh loads, are located in the [lib/](https://github.com/robbyrussell/oh-my-zsh/tree/2b6c502aa5ab56a9db21e90324789a56d83a0cfc/lib) folder, so I did thought about using something like this: `antibody robbyrussell/oh-my-zsh folder:lib`. Although all scripts will indeed be loaded, I was still missing some tweaks from the [oh-my-zsh.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/a1d13aa0b4a794c4f10fdd9d69d59ce2d04c3785/oh-my-zsh.sh) to make autocompletion work.  So loading the [oh-my-zsh.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/a1d13aa0b4a794c4f10fdd9d69d59ce2d04c3785/oh-my-zsh.sh) plugin is **necessary**, because without [this block of code](https://github.com/robbyrussell/oh-my-zsh/blob/a1d13aa0b4a794c4f10fdd9d69d59ce2d04c3785/oh-my-zsh.sh#L62-L78), autocompletion won't work.

Thanks!

**Comment by caarlos0** [comment]
Hi @GUiHKX !

I'm not a user of oh-my-zsh myself, but I'm happy to accept a PR adding this to the docs!

**Comment by jostyee** [comment]
So what's the benefit to use oh-my-zsh along side w/ antibody?

**Comment by GUiHKX** [comment]
@caarlos0 Okay cool, I will try to do that. :+1: 

@akatrevorjay Like I said, oh-my-zsh itself has a lot of [useful plugins](https://github.com/robbyrussell/oh-my-zsh/tree/master/lib) that won't be loaded unless we add that workaround. Personally, I like [autocomplete for commands](https://i.imgur.com/rKjvpYF.png) and [their keybindigs](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh).

**Comment by GUiHKX** [comment]
@caarlos0 Okay cool, I will try to do that. :+1: 

@akatrevorjay Like I said, oh-my-zsh itself has a lot of [useful plugins](https://github.com/robbyrussell/oh-my-zsh/tree/master/lib) that won't be loaded unless we add that workaround. Personally, I like [autocomplete for commands](https://i.imgur.com/rKjvpYF.png) and [their keybindings](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh).

**Comment by seagle0128** [comment]
I'd like vote this request. `oh-my-zsh` is very useful, and `antibody` is very fast. Better integration is better for both IMO.

**Comment by neverfox** [comment]
I don't get any such errors. Is there something else necessary to recreate this?

**Comment by felipe19930** [comment]
@neverfox If you have `source <(antibody init)` in your `~/.zshrc`, every time you run `antibody bundle ...`, antibody will [hide any errors](https://github.com/getantibody/antibody/blob/83893d283d017bbc1b27079fb8b5dfc6b7d58cda/shell/init.go#L13). So, to actually see those errors, you could start a vanilla zsh session and then run `antibody bundle`, like so:

```
$ zsh -f
$ eval $(antibody bundle robbyrussell/oh-my-zsh)
```

**Comment by neverfox** [comment]
@felipe19930 Ah thanks. That also explains why I couldn't statically bundle. Note I did have to change this slightly as on my machine antibody was in `Library/Caches` not `.cache`.

**Comment by felipe19930** [comment]
@neverfox No problem. :) Here's a portable way of setting the `ZSH` variable:

```
ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
```

Maybe @GUiHKX can update his post as well.

**Comment by caarlos0** [comment]
> @neverfox If you have source <(antibody init) in your ~/.zshrc, every time you run antibody bundle ..., antibody will hide any errors. So, to actually see those errors, you could start a vanilla zsh session and then run antibody bundle, like so:

thinking about it, this is probably wrong...

**Comment by TheBaronHimself** [comment]
Big +1. I'd love to see this fixed.
My current workaround is this:

```zsh
#!/bin/zsh

DISABLE_AUTO_UPDATE=true
ZSH="`antibody home`/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"

source <(antibody init)

antibody bundle < ~/.bundles.txt
```

I'm posting this, because using `antibody home` in ZSH works cross-platform.
