### ISSUE TITLE
Sudden issue, probably with proxy

### ISSUE THREAD

**Issue by lroellin** [getantibody/antibody#219]
I currently have an issue with antibody and I don't know how to debug it. After fooling around with networking, I can't get antibody to work again.

All other programs work fine. I have set `HTTP_PROXY` and `HTTPS_PROXY` to the correct proxy, also `http_proxy` and `https_proxy`. This has worked before, and still does for other programs.

When I start my zsh, I get the following. `USERNAME` has been replaced by me.
```
antibody: error: failed to bundle: exit status 128
2018/02/12 15:41:19 git clone failed for https://github.com/zsh-users/zsh-syntax-highlighting Cloning into '/Users/USERNAME/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting'...
fatal: unable to access 'https://github.com/zsh-users/zsh-syntax-highlighting/': Failed to connect to github.com port 443: Connection refused

antibody: error: failed to bundle: exit status 128
2018/02/12 15:41:19 git clone failed for https://github.com/lroellin/zsh Cloning into '/Users/USERNAME/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-lroellin-SLASH-zsh'...
fatal: unable to access 'https://github.com/lroellin/zsh/': Failed to connect to github.com port 443: Connection refused
```

When I do a manual `git clone https://github.com/lroellin/zsh`, it works fine. The variables are set BEFORE the bundle commands. Anyway, it all worked before and only antibody is affected and I don't even know if there's any correlation :)

Is there any way to debug this, any way to enable more verbosity? Or what is causing this?

**Comment by lroellin** [comment]
Ok, after using a direct connection (mobile hotspot) and temporarily disabling proxies, it worked.

To me, this seems like some sort of cache timeout, and I did indeed install antibody and its plugins precisely 1 week ago. Is this what's happening here?

**Comment by caarlos0** [comment]
> To me, this seems like some sort of cache timeout, and I did indeed install antibody and its plugins precisely 1 week ago. Is this what's happening here?

antibody does not have any kind of "timed caching". The `bundle` command downloads the plugins the first time, and after that it just loads them. The `update` command does `git pull` and etc...

It seems that you deleted the `antibody home` folder? Or maybe set the `ANTIBODY_HOME` env to another folder?

Anyway, antibody calls git directly, so it probably is an issue related to git config, not antibody itself...

**Comment by lroellin** [comment]
That is really weird. No, I did not deliberately delete those folders, and git clones works correctly. Now, even `antibody update` works...

If this issue happens again, is there anything I can collect/do to debug this? Anyway, you could close it from my side :)

**Comment by caarlos0** [comment]
I'm afraid there is no proper logging, there is an issue open to add that ( #203 ), but for now the only thing is the output of antibody itself.

maybe trying to run git in verbose mode helps (I think there is an env `GIT_TRACE` or something).

closing this for now, feel free to reopen if needed :)

**Comment by lroellin** [comment]
Hi

I think I've now gotten further into what happens.

It only happens after a week. It seems like after almost exactly one week, ~/Library/Caches/antibody is purged.

I had a watch command running. It showed that the child folders (https-...) were created at May 15 15:33, and now at ~9 the parent folder is gone (I can't confirm when the parent folder, ~/Library/Caches/antibody, was created).

Do you know of any issues here? You're probably using some driver for the Caches thing.

What's weird is that I didn't start zsh or anything when it happened (unless my `watch` command started a new shell each time). Is there anything you know that macOS does with the Caches folder?

The problem is then that I'm in a proxied environment, and something along the way doesn't respect my proxy settings, so I end with a zsh trying to download the bundles when recreating the cache, and running into 443s along the way. The workaround then is to connect to a non-proxied network and download it. Then I'm good for a week.

**Comment by caarlos0** [comment]
Hi @lroellin 

No, the caching folder is just a regular folder where I git clone the repos...

Unfortunately, I don't know... maybe something in your OS is "cleaning up" cache folders or something?

**Comment by lroellin** [comment]
I'll have a look!
