### ISSUE TITLE
Installing fzf

### ISSUE THREAD

**Issue by arsham** [getantibody/antibody#222]
Is there a way to install fzf?

I know with zplug you can do:
```bash
zplug "junegunn/fzf-bin",                        from:gh-r, as:command, rename-to:fzf, use:"*linux*amd64*"
```

**Comment by thiagotalma** [comment]
It would be a great implementation!

**Comment by caarlos0** [comment]
Sorry, I don't have plans of adding this kind of feature.

For the record, I've installed fzf with brew and added this to my config:

https://github.com/caarlos0/dotfiles/blob/master/zsh/config.zsh#L75-L80
