### ISSUE TITLE
Question: update verbosity.

### ISSUE THREAD

**Issue by katsika** [getantibody/antibody#223]
Hey, had a quick look at code and can't see anything that would print information about updated repositories. Does antibody quietly updates repositories? If so, is there a chance some information could be printed to indicate that update was performed?

Thanks.

**Comment by felipe19930** [comment]
I really like the verbosity that `git pull` gives me, and I think something like that would be great for antibody. But probably most people wouldn't like that, specially when you have a considerable amount of plugins. So I think something like `antibody update -v` would be really nice.

**Comment by caarlos0** [comment]
duplicate of #203
