### ISSUE TITLE
Does Antibody work with zsh plugins made in Rust?

### ISSUE THREAD

**Issue by nikitavoloboev** [getantibody/antibody#225]
I wanted to try and use [this plugin](https://github.com/g-plane/zsh-yarn-autocompletions) but when I tried to put it inside my `plugins.txt` and then running `bash install.sh` on new sessions I get this error:

```bash
/Users/nikivi/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-g-plane-SLASH-zsh-yarn-autocompletions/yarn-autocompletions.plugin.zsh:44: command not found: compdef
```

I am curious how can I make this zsh plugin written in Rust work within Antibody?

**Comment by caarlos0** [comment]
`compdef` is a zsh function, I guess you're trying to load the plugin before running `compinit`... probably there is nothing to do with the fact that it's written in rust or antibody per se...

will close, reopen if needed.

**Comment by nikitavoloboev** [comment]
I added `g-plane/zsh-yarn-autocompletions` line in my `plugins.txt` and then ran `install.sh`:
```bash
~/.dotfiles/antibody master*
❯ ls
install.sh	plugins.txt

~/.dotfiles/antibody master*
❯ bash install.sh
Updating all bundles in /Users/nikivi/Library/Caches/antibody...

~/.dotfiles/antibody master*
❯ exec zsh
/Users/nikivi/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-g-plane-SLASH-zsh-yarn-autocompletions/yarn-autocompletions.plugin.zsh:44: command not found: compdef

~/.dotfiles/antibody master*
❯
```

How can I run `compinit` beforehand? I didn't have this problem or similar error with other plugins I use.

Thank you for any help.

**Comment by caarlos0** [comment]
Probably because the some of your plugins already does the compinit thing (they probably shouldn't).

Anyway, the common way is to do this before loading any plugins:

```sh
autoload -Uz compinit
compinit -i
```
