### ISSUE TITLE
Compatibility with FreeBSD

### ISSUE THREAD

**Issue by carlca** [getantibody/antibody#226]
Hello. I have just installed `zsh` on my `FreeBSD` virtual machine running under `Parallels` on an `Apple Mac`. I also have a working `Go 1.10` development system in `FreeBSD`. Can I just do a `go get -u github.com/getantibody/antibody` and then build the binaries and then copy them somewhere so that they are recognised and used by `zsh`? If so, where do I copy the binaries?

**Comment by caarlos0** [comment]
hi @carlca 

you'll need to follow [these steps](https://github.com/getantibody/antibody/blob/master/CONTRIBUTING.md#setup-your-machine), but, instead of `make test`, you can run `make build`. The binary will be in the same folder of the source...

**Comment by carlca** [comment]
Hi @caarlos0

I've just tried to go through the steps you set out but this happened...

![screen shot 2018-03-22 at 20 47 16](https://user-images.githubusercontent.com/260612/37797635-4ad3dba4-2e12-11e8-9d15-9934feb161f0.png)
  
Any ideas?

**Comment by carlca** [comment]
No worries (I think!). I did a `go get -u github.com/getantibody/antibody` and that seemed to grab everything okay.

**Comment by carlca** [comment]
I spoke too soon!

![screen shot 2018-03-22 at 20 57 37](https://user-images.githubusercontent.com/260612/37798141-c475fb4e-2e13-11e8-98a8-1b216f36a6e2.png)

**Comment by caarlos0** [comment]
can you paste the output of `go env` here please?

**Comment by carlca** [comment]
![screen shot 2018-03-23 at 02 04 26](https://user-images.githubusercontent.com/260612/37807686-a279eaac-2e3e-11e8-9dde-74ba3fc624ab.png)

**Comment by carlca** [comment]
![screen shot 2018-03-23 at 02 10 55](https://user-images.githubusercontent.com/260612/37807864-85399cb6-2e3f-11e8-8531-3efeb39df27e.png)

**Comment by carlca** [comment]
No worries, I'm trying out Prezto now. I'm already running it on my Apple Mac. Just running up against some font issues at the moment. All good fun though!

**Comment by rspeed** [comment]
I made a PR for this: caarlos0/gohome#8

**Comment by caarlos0** [comment]
thanks @rspeed , releasing v3.4.6 for freebsd as well!
