### ISSUE TITLE
Beginners guide (zsh from scratch)

### ISSUE THREAD

**Issue by will-stone** [getantibody/antibody#229]
Hi. Thanks for this project. It certainly seems to be the fastest plugin manager I've found so far for Zsh. However, I can't seem to figure out how to setup a basic `.zshrc` file and which order to put items. Would you mind adding a _from scratch_ / starter guide? i.e. someone installing zsh + antibody coming from Bash, maybe include some basic options / plugins, completions, syntax highlighting, and search up / down.

For example, I can `brew install zsh` then run the oh-my-zsh install script and I'm away, and only need worry about adding plugins, but this setup gets very slow after adding a few plugins. It'd be great to get Antibody up and going with such ease too.

**Comment by caarlos0** [comment]
Hi @will-stone !

I think it would be nice, but it's not the focus of this repo... 

Comparing oh-my-zsh with antibody is also not fair. oh-my-zsh is a framework and goes way beyond adding plugins and etc... Antibody just manages plugins fast... nothing more :) 

Will close this :)

**Comment by will-stone** [comment]
Ok, no worries. If anyone else stumbles upon this and can point me to a simple zsh config with Antibody, I'd be most appreciative.

**Comment by caarlos0** [comment]
my dotfiles are quite simple and use antibody, maybe you can learn from them :)

https://github.com/caarlos0/dotfiles
