### ISSUE TITLE
A plugin uses `autoload`, but `$fpath` is not extended by Antibody

### ISSUE THREAD

**Issue by psprint** [getantibody/antibody#232]
Hello,
an Antibody user reported (https://github.com/zdharma/fast-syntax-highlighting/issues/21) a problem with `zdharma/fast-syntax-highlighting` plugin. Quick investigation showed that Antibody didn't extend `$fpath` for this plugin. Plugin expects its main file to be sourced, and its directory to be added to `$fpath`, so that completions and autoload functions work.

I wonder why FSH doesn't have `$fpath` entry, and `zsh-users/zsh-completions` does have it?

**Comment by caarlos0** [comment]
Hi, it doesn't do anything different for specific plugins... antibody never adds the folder to fpath.

I'll fix that.

**Comment by caarlos0** [comment]
check ##233

**Comment by psprint** [comment]
Great. I've realized that `zsh-users/zsh-completions` uses subdirectory `.../src` and handles this directory by itself, i.e. manually adds it to fpath, hence the difference between plugins.

**Comment by caarlos0** [comment]
yeah, I'm not sure which one is the best way... this issue of fpath never came up before...

**Comment by psprint** [comment]
It is weird, completions wouldn't work, apparently no one used completions. I'm really certain plugin manager should update $fpath, I'm author of zplugin and I create a [plugin standard](https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc), I'm really into this, you can trust me.
