### ISSUE TITLE
Unable to clone plugin repos

### ISSUE THREAD

**Issue by dominik-zeglen** [getantibody/antibody#234]
Tonight I installed antibody on brand new Ubuntu using the provided script, then created a file with plugin list and ran `antibody bundle` command. That's what I got:
```
$ antibody bundle < ~/.zsh-plugins > ~/.zsh-plugins.sh
antibody: git clone failed for https://github.com/sindresorhus/async Cloning into '/home/anders/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-sindresorhus-SLASH-async'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
antibody: error: failed to bundle: exit status 128
```

I'm using 2FA if it matters. Got any idea how to deal with this and why git wants to ask me for credentials?

**Comment by caarlos0** [comment]
the error is desirable, yes, the repo doesn't exist.
