### ISSUE TITLE
Broken CSS on getantibody.github.io

### ISSUE THREAD

**Issue by matiaskorhonen** [getantibody/antibody#235]
The styles and JavaScript fail to load on getantibody.github.io:

<img width="1536" alt="2018-06-13_14-24-04_jmvtc" src="https://user-images.githubusercontent.com/43314/41348495-717cff94-6f15-11e8-94db-3b2cfe630ad9.png">

**Comment by caarlos0** [comment]
hmm, I think I broke it yesterday :/

sorry, will try to fix this today

thanks for reporting!

**Comment by caarlos0** [comment]
/remind me this issue in 8 hours
