### ISSUE TITLE
Could not resolve host github.com

### ISSUE THREAD

**Issue by mike-code** [getantibody/antibody#236]
I spent some time making antibody working on Windows' cygwin environment and I was happy to have it finally running but...

```
Mike@MIKEHOME:~% antibody bundle eendroroy/alien-minimal
antibody: git clone failed for https://github.com/eendroroy/alien-minimal Cloning into 'C:\Users\Mike\AppData\Roaming\antibody\https-COLON--SLASH--SLASH-github.com-SLASH-eendroroy-SLASH-alien-minimal'...
fatal: unable to access 'https://github.com/eendroroy/alien-minimal/': Could not resolve host: github.com

antibody: error: failed to bundle: exit status 128
```

There's nothing blocking internet access to the application as well as (obviously) I can clone repository if I just type `git clone` in the terminal.

How does antibody try to resolve a domain?

**Comment by caarlos0** [comment]
antibody uses `git clone` underneath, nothing special, you can check here: https://github.com/getantibody/antibody/blob/master/project/git.go#L77-L82

**Comment by caarlos0** [comment]
closing as it does not seem to be an issue with antibody.
