### ISSUE TITLE
add more than 1 plugin from oh-my-zsh

### ISSUE THREAD

**Issue by freddiaN** [getantibody/antibody#238]
It seems like I can't add more than 1 plugin from `oh-my-zsh`, since it seems like the `folder:` option only takes 1 argument and I can't add multiple `robbyrussell/oh-my-zsh` lines, since it will then complain about that repository already existing in `$HOME/.cache/antibody`. Is there a fix for this?

**Comment by zchfvy** [comment]
I had the same issue after following the recommended install steps (curl). However downloading a binary from the GitHub releases page fixed it. I guess it's out of date on the website?

**Comment by freddiaN** [comment]
How did you do it after you downloaded the binary, just 1 line for each plugin?

**Comment by freddiaN** [comment]
OK, so giving each module their own line seemd to have worked with a fresh binary (the one from the releases tab didn't work, so I just `go get`'d it), but now I get a bunch of errors complaining that it can't find the command `compdef` and the `npm` module doesn't have permissions for the folder `/npm_completion`
