### ISSUE TITLE
Complete does not work

### ISSUE THREAD

**Issue by thiagotalma** [getantibody/antibody#242]
Hello Carlos,

I could not figure out why the completion defined this way in the plugin does not work with the antibody.
https://github.com/owenstranathan/pipenv.zsh/blob/master/pipenv.plugin.zsh#L18

Is there anything I can do to work?

Abraço!

**Comment by caarlos0** [comment]
/remind me this issue in 8 hours

**Comment by caarlos0** [comment]
antibody does not do anything specifically about this.

if it doesn't work, maybe it's a bug on the plugin itself?

have you tried it with other plugin managers?

**Comment by thiagotalma** [comment]
It really is not an Antibody problem. Excuse me!

I discovered that completion works when I comment this .zshrc line:
https://github.com/caarlos0/dotfiles/blob/master/zsh/zshrc.symlink#L34

Anyway, if you want to give some idea to solve, I would be grateful!  😉

**Comment by caarlos0** [comment]
```zsh
autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi
```

`compinit -C -i` loads completions from the cache, and `compinit -i` is without cache, which is slower.

I didn't analyze the plugin you linked, so I don't know why this matters for it, you should probably open an issue to that plugin... :)
