### ISSUE TITLE
Antibody cache directory disappears (seemingly) at random

### ISSUE THREAD

**Issue by ErikFontanel** [getantibody/antibody#243]
I've been using Antibody for a while now and for the last 6 or so months the antibody directory containing all the bundles disappears from my system. It happens at random intervals (between a few days ~ some weeks). When I launch a new shell, I'm greeted with a bare zsh shell. Running `antibody bundle < zsh-bundles.txt > zsh-bundles.sh` fixes it, but I might not be the only one experiencing this issue. 

As far as I'm aware, it only seems to happen with the `antibody` directory and I do not have any cleanup scripts running.

I'm running High Sierra 10.13.5.

Keep up the good work :)

**Comment by caarlos0** [comment]
weird...

You are using it in the "static mode", right?

If so, antibody only runs when you run it... the `zsh-bundles.sh` on your example will be only like `source path/foo.zsh`...

Maybe one of the plugins you're using is doing something funky?

**Comment by ErikFontanel** [comment]
Weird indeed :D 

Indeed I'm using static mode and the bundles file only sources bundles. Which all fail when they paths are removed from Caches.

Could be a rogue plugin or some 'cleaning' script. I'll investigate further…

**Comment by SirNerdBear** [comment]
I noticed this too and I figured out, in my case, CleanMyMac was removing the cache files for antibody. I added it to the ignore list in case this helps anyone with the same issue. 

On a side note if you're using static mode shouldn't antibody be using ~/Libary/antibody as it isn't a cached item (it's stored permanently). A cache by nature is supposed to be purgeable without causing an issue.

**Comment by caarlos0** [comment]
Yeah, antibody doesn't know if you're using it statically or not... maybe we can add a note to the readme though...

**Comment by ErikFontanel** [comment]
nice find @SirNerdBear, although I'm not using Clean My Mac, it makes sense to empty caches every now and then. I'll move the Antigen folder and get rid of my auto reinstaller

**Comment by caarlos0** [comment]
BTW: you can change the folder with the `ANTIBODY_HOME` environment variable...
