### ISSUE TITLE
Consider branch on antibody update

### ISSUE THREAD

**Issue by texhnolyze** [getantibody/antibody#246]
First off thanks for this cool project!

Just got to using it and have an issue/feature request with the `antibody update` functionality:

I am using this [zsh plugin](https://github.com/soimort/translate-shell) for translations, which weirdly does not update the master branch and only has the latest updates on the release tags and the develop branch.

So using a `.zsh_plugins.txt` containing: ```soimort/translate-shell branch:develop``` works fine until I want to update all my plugins with `antibody update` as it tries to update to the master branch (which is actually behind and diverged). This is obviously the translation projects issue not yours! 

But it got me thinking if I use and specify branch of a project in my plugins shouldn't the update functionality just update the git repo within that branch as I might want to test experimental functionality or new features etc?

What's your opinion on that? I would be happy to do a pull request if you share my viewpoint, otherwise I'll see if I can get the other projects maintainer to merge new releases on master (which should be done anyway in my opinion).

**Comment by caarlos0** [comment]
yeh that makes sense I think...
