### ISSUE TITLE
Is it possible to not include https-COLON--SLASH--SLASH in Caches names?

### ISSUE THREAD

**Issue by nikitavoloboev** [getantibody/antibody#248]
I find the naming of it and it being fully uppercased quite annoying and it makes it hard to search through the folder of all the caches too:

![2018-08-02 at 10 18](https://user-images.githubusercontent.com/6391776/43571489-5d016e66-963d-11e8-8a11-5cd475d7b42d.png)

Is it possible to perhaps remove this text from the names? I think it will make everything look much cleaner.

**Comment by caarlos0** [comment]
no, it is like this by design. 

Its the same patter used by antigen.
