### ISSUE TITLE
Support for changing branches of currently installed plugin?

### ISSUE THREAD

**Issue by cole-h** [getantibody/antibody#250]
If I want to switch branches on a currently installed plugin, is there any way to do that? It's not something I do often, but when I want to test a new pull on one of my addons, it would be nice to just `antibody bundle xxx` or `antibody update` and have it checkout whatever branch is specified. Note: I am statically updating my plugins.

My solution was to move the `master` version of the plugin to another folder and re-`antibody bundle xxx` for it to pull in the new branch.

I only recently started using Antibody so let me know if I overlooked something.

**Comment by caarlos0** [comment]
I think that's not a common use case, so I rather not do it... you can always just delete everything with `antibody purge PLUGIN` and run `antibody bundle` it again.
