### ISSUE TITLE
[Documentation] Setup without root

### ISSUE THREAD

**Issue by binaryplease** [getantibody/antibody#253]
Hello, 
is it possible to use antibody without root?
On my home machine (Linux Arch) I have antibody installed via AUR, so everything works as documented. I have been using zplug before, which allowed me to setup new hosts with my dotfiles via a bootstrap script (https://github.com/binaryplease/dotfiles/blob/master/bootstrap.sh) from a github or gitlab repo.

Setting up everything was as simple as doing:
```
curl -Lks https://gitlab.com/binaryplease/dotfiles/raw/master/bootstrap.sh | /bin/bash
```

Antibody really is *much* faster in starting new shells, so I would like to fully migrate to it. Is there a way to script the installation like I did with zplug? I sometimes have to work on hosts on which I have no root permissions, so it would be nice to have a way to set it up with as little dependencies/requeirements as possible. Any ideas?

**Comment by caarlos0** [comment]
yes, you shouldn't need root to use antibody, maybe just to install the package itself, but you should be able to run it as a regular user without any problems.

if you can't that's a problem in the aur package (non official).
