### ISSUE TITLE
Static loading not working

### ISSUE THREAD

**Issue by Kronuz** [getantibody/antibody#256]
I'm trying the static loading method for antibody (version 3.6.0):

```sh
antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
```

This is my `.zsh_plugins.txt`:

```
zdharma/fast-syntax-highlighting
zsh-users/zsh-autosuggestions
zsh-users/zsh-history-substring-search
zsh-users/zsh-completions

mafredri/zsh-async
intelfx/pure
```

But it's producing an empty `zsh_plugins.sh` file... am I missing something?

**Comment by caarlos0** [comment]
probably you ran `source <(antibody init)` at some point. If so, you need to start a clean shell.

**Comment by h3adache** [comment]
Hi @caarlos0, sorry I'm confused why this is closed.
The [usage](https://getantibody.github.io/usage/) doc seems to say to run `source <(antibody init)` before running bundle.
