### ISSUE TITLE
Can't use oh-my-zsh anymore

### ISSUE THREAD

**Issue by tobiastimm** [getantibody/antibody#259]
`brew` installed the update to `3.7.0`. After that I get an error when I try to use an `oh-my-zsh` plugin.

```
antibody bundle robbyrussell/oh-my-zsh
zsh: can't open input file: /tools/check_for_upgrade.sh
/Users/ttimm/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/oh-my-zsh.sh:34: no matches found: /lib/*.zsh
```

With `3.6.0` everything works fine.

**Comment by skyuplam** [comment]
According to the commit 3ebbfb3b79c558712fd1789c988257a450809689, `folder` has been replaced by `path`. Update your config by replacing `folder` to `path` should solve your issue.

**Comment by IgnusG** [comment]
Thanks @skyuplam that fixed the issue.
 
Nonetheless, this should have then been a major not a minor update, since it changes behavior of an existing option.

**Comment by caarlos0** [comment]
You're right, it should have been a major. Will cut v4.0.0.

**Comment by caarlos0** [comment]
Done, I removed the v3.7.0 as it was misleading, cut v4.0.0 and released.

**Comment by caarlos0** [comment]
Thanks for pointing this out, sorry for the trouble.
