### ISSUE TITLE
Equivalent of 'antigen use oh-my-zsh'

### ISSUE THREAD

**Issue by aserrallerios** [getantibody/antibody#261]
Hello,

I'm switching from `antigen` to `antibody`, and everything is working fine, except for the load of the `oh-my-zsh`.

It looks like I was relying on it more than I was aware of:

* autoload & compinit stuff
* default zsh key bindings
* ENV variables used by several `oh-my-zsh` plugins

I was wondering if there's a comprehensive solution to load all the `oh-my-zsh` stuff from antibody.

BTW this obvious solution is not working
```sh
antibody bundle robbyrussell/oh-my-zsh
antibody bundle robbyrussell/oh-my-zsh path:plugins/aws
```
just because it depends on the local `oh-my-zsh` installation.

`antigen` managed to make it work with the trick:
```sh
antigen use oh-my-zsh
```
Should I just install `oh-my-zsh` locally (and modify the `.zshrc` accordingly) instead of relying on something like the `antigen` trick?

**Comment by mattbailey** [comment]
@aserrallerios 	from other issues, this is how I fixed it:

in .zshrc:

```zsh
source <(antibody init)
ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
antibody bundle robbyrussell/oh-my-zsh
antibody bundle robbyrussell/oh-my-zsh folder:plugins/common-aliases
antibody bundle "
  robbyrussell/oh-my-zsh path:plugins/battery
  robbyrussell/oh-my-zsh path:plugins/brew
"
```

**Comment by caarlos0** [comment]
you can just 

```
antibody bundle "
  robbyrussell/oh-my-zsh path:plugins/aws
  robbyrussell/oh-my-zsh path:plugins/battery
  robbyrussell/oh-my-zsh path:plugins/brew
"
```

about compdef -> https://github.com/robbyrussell/oh-my-zsh/issues/3356

antibody does not and will not do anything special with oh-my-zsh or any other kind of plugin.

**Comment by caarlos0** [comment]
you could also have your locally managed oh-my-zsh installation and point antibody to it, for example, if you have it on your home:

```
antibody bundle "
  /home/foo/oh-my-zsh path:plugins/aws
  /home/foo/oh-my-zsh path:plugins/battery
  /home/foo/oh-my-zsh path:plugins/brew
"
```

**Comment by aserrallerios** [comment]
Thanks @mattbailey, it worked!

@caarlos0 the problem it's with the "framework", not with the individual plugins, I get that `antibody` won't do any special treatment to `oh-my-zsh` and I totally agree on that being the best option.

The thing is that anybody migrating from:

* oh-my-zsh
* antigen (antigen use oh-my-zsh)
* zgen (zgen oh-my-zsh)
* maybe others

will have the exact same issue. The best solution may be to just hint this problem and multiple solutions/workarounds on the `antibody` documentation.

**Comment by caarlos0** [comment]
yeah, better documentation would be great! 

If you find what works, we can definitely do that :D

**Comment by mattmc3** [comment]
I found a pretty simple way to handle oh-my-zsh. In your .zshrc:

```zsh
# where is antibody keeping its stuff
ANTIBODY_HOME="$(antibody home)"
# set the theme to something, or blank if you use a non omz theme
ZSH_THEME=
# you can do plugins the omz way if you want... or load with antibody later
plugins=(
	git
)
export ZSH="$ANTIBODY_HOME"/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh

# omz!
antibody bundle robbyrussell/oh-my-zsh
# this is the antibody way of loading omz plugins
antibody bundle robbyrussell/oh-my-zsh path:plugins/colored-man-pages 
```

**Comment by NightMachinary** [comment]
What's the advantage of using antibody to manage oh-my-zsh versus just letting both of them coexist? (I've been doing that with no problems so far ...)

**Comment by louy2** [comment]
Note that if you install oh-my-zsh normally then modify the `.zshrc` to use antibody, then

    source $ZSH/oh-my-zsh.sh

should be before

    source <(antibody init)
    source < .zsh_plugins.sh

or you'd see the `compdef` error too.

**Comment by mhalano** [comment]
I'm doing some research and I found this line works very well:
antibody bundle robbyrussell/oh-my-zsh path:lib
Using this I can have all core features like, multi-session history, working fine.

**Comment by tekumara** [comment]
NB: compinit needs to be run first to avoid *command not found: compdef* errors

This works for me:
```
autoload -Uz compinit && compinit -C

source <(antibody init)
antibody bundle ohmyzsh/ohmyzsh path:lib
antibody bundle ohmyzsh/ohmyzsh path:themes/robbyrussell.zsh-theme
```

**Comment by IlanFrumer** [comment]
A workaround using `kind:dummy`

```zsh
source <(antibody init)
antibody bundle robbyrussell/oh-my-zsh kind:dummy
export ZSH=$(antibody path robbyrussell/oh-my-zsh)
ZSH_THEME="robbyrussell"
antibody bundle robbyrussell/oh-my-zsh
```
