### ISSUE TITLE
Antibody cant load single file permission denied.

### ISSUE THREAD

**Issue by iboyperson** [getantibody/antibody#266]
I am attempting to load this "robbyrussell/oh-my-zsh path:lib/completion.zsh" however when launching a shell I get this error: 

    /home/iboyperson/.zsh_plugins.sh:8: permission denied: /home/iboyperson/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh/lib/completion.zsh

**Comment by jas99** [comment]
Hey @caarlos0 @pragmaticivan 
+1 
`robbyrussell/oh-my-zsh path:lib/clipboard.zsh`
I was trying to load and was also geting permission denied.

Thx

**Comment by weilbith** [comment]
Why has this been closed. Any suggestions how to circumvent this, despite from setting the permissions manually?

**Comment by weilbith** [comment]
I'm still getting this error, even after build the AUR package new to be sure using the most recent build.

**Comment by caarlos0** [comment]
just tried `robbyrussell/oh-my-zsh path:lib/clipboard.zsh` example here and it works fine...
