### ISSUE TITLE
Add local antibody install script

### ISSUE THREAD

**Issue by binaryplease** [getantibody/antibody#268]
Hello, 

I often have to work on servers on which I don't have root permissions and can't use sudo or write to `/usr/local/bin`, which the antibody install script at `https://git.io/antibody` requires.

Would you be willing to add a local install variant?
I use the following script, which is a modification of yours and saves to `~/.local/bin/antibody`. I have that path in my $PATH variable likes so:
```
export PATH="$PATH:.local/bin:
```
this way it works just as well and doesn't require root permissions. My modified script is

```bash
#!/bin/sh
set -e
DOWNLOAD_URL="https://github.com/getantibody/antibody/releases/download"
test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"

last_version() {
  curl -s https://raw.githubusercontent.com/getantibody/homebrew-tap/master/Formula/antibody.rb |
    grep url |
    cut -f8 -d'/'
}

download() {
  version="$(last_version)" || true
  test -z "$version" && {
    echo "Unable to get antibody version."
    exit 1
  }
  echo "Downloading antibody $version for $(uname -s)_$(uname -m)..."
  rm -f /tmp/antibody.tar.gz
  curl -s -L -o /tmp/antibody.tar.gz \
    "$DOWNLOAD_URL/$version/antibody_$(uname -s)_$(uname -m).tar.gz"
}

extract() {
  tar -xf /tmp/antibody.tar.gz -C "$TMPDIR"
}

download
extract || true
mv -f "$TMPDIR"/antibody ~/.local/bin/antibody
which antibody
```
I suppose other users could profit from this too, maybe you want to maintain a `https://git.io/antibody-local` variant or allow to pass a parameter to the existing script.

Cheers,

Pablo

**Comment by caarlos0** [comment]
can you try:

```sh
curl -sfL https://install.goreleaser.com/github.com/getantibody/antibody.sh | sh
```

**Comment by binaryplease** [comment]
> can you try:
> 
> ```shell
> curl -sfL https://install.goreleaser.com/github.com/getantibody/antibody.sh | sh
> ```

Almost works. It places the binary in ~/bin/antibody. I think putting it in a `.local` (note leading dot) would be cleaner.

**Comment by caarlos0** [comment]
the script is auto-generated... it supports a lot more things than the current one...

**Comment by re1** [comment]
Why not just update the movement line to fallback to user binaries?
Here are two possible solutions:

```sh
# reacts to error on movement
mv -f "$TMPDIR"/antibody /usr/local/bin/antibody || mv -f "$TMPDIR"/antibody ~/.local/bin/antibody
```

```sh
# tests write access before movement
[ -w '/usr/local/bin' ] && mv -f "$TMPDIR"/antibody /usr/local/bin/antibody || mv -f "$TMPDIR"/antibody ~/.local/bin/antibody
```

```sh
# or a little more clean
[ -w '/usr/local/bin' ] && DEST=/usr/local/bin || DEST=~/.local/bin
mv -f "$TMPDIR"/antibody "$DEST"/antibody
```

This would also fix the issue for @binaryplease. Alternatively you could just look out for an environment variable containing the install path like this:

```sh
# check for DEST variable
[ -z ${DEST+x} ] || $([ -w '/usr/local/bin' ] && DEST=/usr/local/bin || DEST=~/.local/bin)
mv -f "$TMPDIR"/antibody "$DEST"/antibody
```

**Comment by MarioRicalde** [comment]
Sounds like a nice thing to have. 👍

**Comment by Hydrotoast** [comment]
I agree with @binaryplease that an option to install to `~/.local/bin/antibody` is preferable for at least two reasons:
1. shared-user Linux environments, such as university/corporate clusters, typically do not allow nonadmin users to install software on `/usr`; and
2.  the plugins are already stored in `~/.cache/antibody`, so having the binary in `~/.local/bin/antibody` may provide a more consistent user experience.

@re1, that's a very clean solution to this problem with few diffs. :) Although it would likely break the clever use of eager evaluation here, I think it should also log/print the chosen installation directory.

**Comment by Hydrotoast** [comment]
Sorry, I didn't notice earlier, it looks like there's a separate repo for the installer: https://github.com/getantibody/installer. FYI for anyone else looking to improve the installer. :)

**Comment by caarlos0** [comment]
should be fixed in https://github.com/getantibody/installer/commit/b06e4a8dace1bf0b95f1b041ecc8a0f6f95acb3a
