### ISSUE TITLE
Completion scripts fail when "sourced"

### ISSUE THREAD

**Issue by aserrallerios** [getantibody/antibody#269]
Hello,

According to the issue https://github.com/getantibody/antibody/issues/217 it looks like antibody does supports completion scripts. The problem is that some of the completion scripts don't allow to be sourced, and they don't come with `plugin.zsh` file:

https://github.com/Linuxbrew/brew/tree/master/completions/zsh

Adding this bundle does nothing:

    Linuxbrew/brew path:completions/zsh

Adding this bundles makes antibody fail:

    Linuxbrew/brew path:completions/zsh/_brew
    Linuxbrew/brew path:completions/zsh/_brew_cask
&nbsp;

    _arguments:comparguments:325: can only be called from completion function
    _arguments:comparguments:325: can only be called from completion function

The problem fades away if you just create an empty file called `something.plugin.zsh` in the completions folder and add:

    Linuxbrew/brew path:completions/zsh

Is there any way for antibody to just fpath the files in the folder or path without trying to source them first?

**Comment by caarlos0** [comment]
would #270 solve the issue?

**Comment by aserrallerios** [comment]
Wow that was fast! Cannot test it right now but it looks like it's exactly what we need. Thank you!

**Comment by caarlos0** [comment]
should be possible on latest, also check docs http://getantibody.github.io/options/

cheers!
