### ISSUE TITLE
Help loading tmuxinator plugin

### ISSUE THREAD

**Issue by aserrallerios** [getantibody/antibody#273]
Hello,

The [tmuxinator](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/tmuxinator) plugin of oh-my-zsh contains two files, one is the zsh plugin, and the other is a completions file that needs to be sourced.

I wonder which is the right way for loading it using antibody. The only way I've managed to load it is using this workaround:

    robbyrussell/oh-my-zsh path:plugins/tmuxinator/tmuxinator.plugin.zsh
    robbyrussell/oh-my-zsh path:plugins/tmuxinator/_tmuxinator

If I just load the plugin's path, the completions are not working.

    robbyrussell/oh-my-zsh path:plugins/tmuxinator

There's something I'm missing? It's a limitation of antibody? It's a poorly designed plugin structure?

Thanks.

**Comment by caarlos0** [comment]
I think that if you do:

```
robbyrussell/oh-my-zsh path:plugins/tmuxinator
robbyrussell/oh-my-zsh path:plugins/tmuxinator/_tmuxinator
```

it should work.

the problem seems to be the name of the completions file...
