### ISSUE TITLE
Weird error with static load (antibody snap)

### ISSUE THREAD

**Issue by aserrallerios** [getantibody/antibody#274]
Empty `.zshrc`.

When I try to load antibody statically:

```sh
antibody bundle < ~/dotfiles/zsh_plugins.txt > ~/.zsh_plugins.sh
```

I got a bunch of `git` errors, one per plugin:

```
antibody: git clone failed for https://github.com/molovo/tipz
antibody: error: failed to bundle: exec: "git": executable file not found in $PATH
```

Of course, `git` is in the PATH.

```sh
% antibody -v
antibody version 4.1.0
% antibody home
/home/aserralle/snap/antibody/10/.cache/antibody
% git --version
git version 2.20.1
% which git
/usr/bin/git
```

Any idea on what's going on?

**Comment by caarlos0** [comment]
weird, what is the output of `echo $PATH`?

**Comment by aserrallerios** [comment]
```sh
% echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
```

**Comment by caarlos0** [comment]
`/usr/bin` is not in `PATH`...

**Comment by aserrallerios** [comment]
It's the third one, right?

**Comment by caarlos0** [comment]
oh, right..

**Comment by caarlos0** [comment]
oh, you are using the snap package... so I bet the problem is on the snap... probably it can't see git...

**Comment by aserrallerios** [comment]
Makes sense... Do you think the snap should add an "interface" to be able to run git? I'm pretty new to snaps, so I don't know if that's even possible. Another option is to bundle git into the snap.

**Comment by caarlos0** [comment]
yeah, not sure either... I have a wip removing the dependency on git, actually... maybe it's easier to just focus on that...

**Comment by caarlos0** [comment]
I think I'll just unpublish the snap, as it does not work anyway.

**Comment by caarlos0** [comment]
removed from the store.

Please install it using any  of the other methods.

Sorry about the issue.
