### ISSUE TITLE
Brew (linuxbrew) install doesn't work

### ISSUE THREAD

**Issue by aserrallerios** [getantibody/antibody#277]
```bash 
% brew install getantibody/tap/antibody
...
% which antibody
antibody not found
% chmod a+x /home/linuxbrew/.linuxbrew/Cellar/antibody/4.1.0/bin/antibody
% antibody
zsh: exec format error: antibody
```

**Comment by caarlos0** [comment]
yeah, it is not compatible with linuxbrew...

**Comment by aserrallerios** [comment]
Should it be as easy as to add an `if OS.mac?` clause to the formula?

**Comment by caarlos0** [comment]
not sure... I asked on the foruns... also, the formula is generated by GoReleaser, so the change would be there...

**Comment by Arslanbekov** [comment]
Before`install` need run `brew tap getantibody/tap`

**Comment by caarlos0** [comment]
> Before`install` need run `brew tap getantibody/tap`

not really

**Comment by caarlos0** [comment]
can you try again please?

**Comment by caarlos0** [comment]
just tested it here with

```sh
docker run --rm -it linuxbrew/linuxbrew bash 
brew install getantibody/tap/antibody
```
