### ISSUE TITLE
Broken docs pages

### ISSUE THREAD

**Issue by OdinsHat** [getantibody/antibody#278]
The following docs have been written with script HTML tags in them. But script tags are not allowed in Git Markdown. So the pages just hjave a load of ugly broken source instead of the charts they're meant to show:

* https://github.com/getantibody/antibody/blob/master/www/content/fast.md
* https://github.com/getantibody/antibody/blob/master/www/content/intro.md

**Comment by caarlos0** [comment]
the docs are on http://getantibody.github.io/

those are the sources.

**Comment by caarlos0** [comment]
also removed the link from the readme, thanks for reporting ;)
