### ISSUE TITLE
Install script fails with clueless message

### ISSUE THREAD

**Issue by mperezi** [getantibody/antibody#279]
When I "exec" `git.io/antibody` to bootstrap the install process on my machine it exits with this weird message:

> Downloading antibody v4.1.0 for Linux_armv7l...
> tar: This does not look like a tar archive
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> mv: cannot stat '/tmp/tmp.TZytgPNqeR/antibody': No such file or directory

I'm on a cloud server where `uname -m` outputs `armv7l` and it turns out there is no package available for this exact hardware, although it does for `armv7` (btw: I installed the latter and it worked out fine)

The thing is... couldn't it be the error message more informative?

**Comment by caarlos0** [comment]
thanks for reporting!

**Comment by insuusvenerati** [comment]
I manually installed antibody for armv7 on my armv71 machine and so far it's working fine. Just FYI. Sorry to necro an old bug.

**Comment by caarlos0** [comment]
can you verify if `curl -sfL https://install.goreleaser.com/github.com/getantibody/antibody.sh | sh` works?

**Comment by wmute** [comment]
I had the same issue with the installation script from the website. This new one works.

**Comment by caarlos0** [comment]
should be fixed in https://github.com/getantibody/installer/commit/b06e4a8dace1bf0b95f1b041ecc8a0f6f95acb3a
