### ISSUE TITLE
remove antibody completely or reset installation

### ISSUE THREAD

**Issue by ulfw** [getantibody/antibody#280]
I have some troubles with antibody after purging a plugin.
Starting the terminal responds with "
antibody: git clone failed for https:///...
fatal: multiple updates for reference 'refs/remotes/origin/master' not permitted."
(message translated from german language, maybe it uses other words in english environment)

ANTIBODY_HOME is empty

Is there any way to "reset" the installation to start from scratch oder remove antbody with all preferences?

**Comment by caarlos0** [comment]
you can remove the entire antibody home dir:

```sh
rm -rf $(antibody home)
```

and then, of course, stop calling the plugin on your zshrc...

**Comment by ulfw** [comment]
just for information: the problem is the just installed update for git 2.21 using homebrew, its causing an error on every clone

**Comment by caarlos0** [comment]
🤔

let me verify that

**Comment by caarlos0** [comment]
worked as usual here... 

> antibody: git clone failed for https:///...

seems like too many `///`... mind to share the exact commands you're running and the plugins you're using?

**Comment by ulfw** [comment]
I mean its a problem with git itself, not related to antibody.
OSX System git 2.17 works fine.

**Comment by caarlos0** [comment]
I'm using the same git version and everything works as expected... I think you're passing a wrong URL to antibody to download or something

**Comment by ulfw** [comment]
No, I did not pass any urls to antibody, just typed "antibody bundle ..."

Now, as I am at home, I reinstalled git via homebrew and it works, no idea what happened.

As I said, I could not clone any git repository. There was always an error message.

Case closed...

**Comment by caarlos0** [comment]
weird 🤔
