### ISSUE TITLE
Provide automatic static loading script in documentation

### ISSUE THREAD

**Issue by owm111** [getantibody/antibody#281]
The documentation only provides the "manual" way to do static loading (i.e. "recompiling" the bundle script every time the plugin list is edited), but why not just do it automatically?
```sh
# .zshrc
if [[ ! -e "~/.zsh_plugins.sh" ]] || [[ "~/.zsh_plugins.txt" -nt "~/.zsh_plugins.sh" ]]; then
  antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
fi
source ~/.zsh_plugins.sh
```
But I may be misunderstanding something.

**Comment by caarlos0** [comment]
its your choice... in my case it's not worth it as I don't change my plugin list often..
