### ISSUE TITLE
Kudos! Antibody is blazingly fast!

### ISSUE THREAD

**Issue by MarioRicalde** [getantibody/antibody#282]
This is not really an issue, I just wanted to deliver some praise.

For the past couple of days, I was browsing around for some managers. Decided to go with zplug because the readme made a big deal about how fast it was. Once I had everything with it, I began doing some benchmarking and I noticed that I was getting consistently 800ms-1.2s load times. After trimming it down, I could only get it down to around 600ms.

Today I decided to switch to antibody and I was quite surprised.

Same configuration, with dynamic loading:

![image](https://user-images.githubusercontent.com/125900/53631167-895b9a00-3bd7-11e9-9649-2e1a82f47274.png)

And with static loading:

![image](https://user-images.githubusercontent.com/125900/53631178-937d9880-3bd7-11e9-92ba-978e9d96e173.png)

Absolutely outstanding, great job!

**Comment by MarioRicalde** [comment]
Closing as this is not an issue 👍

**Comment by caarlos0** [comment]
awesome! Thanks for the kind words =D
