### ISSUE TITLE
robbyrussell/oh-my-zsh plugins dynamically

### ISSUE THREAD

**Issue by artivilla** [getantibody/antibody#285]
So I followed the instructions on the site [usage](https://getantibody.github.io/usage/). Is this the correct form to load oh-my-zsh plugins?

Using the latest v 4.1.1 with the following
~/.zshrc
```
export ANTIBODY_HOME=~/Libary/antibody
antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
source ~/.zsh_plugins.sh
```
and ~/.zsh_plugins.txt
```

#plugins

robbyrussell/oh-my-zsh path:plugins/aws/aws.plugin.zsh

zsh-users/zsh-syntax-highlighting
zsh-users/zsh-history-substring-search

#theme
mafredri/zsh-async
sindresorhus/pure
```

The theme loads, it's oh the oh-my-zsh plugins that dont' work.

**Comment by caarlos0** [comment]
hi!

I just tested the `robbyrussell/oh-my-zsh path:plugins/aws/aws.plugin.zsh` line here, and the `aws` plugin was loaded...

not sure what is the issue you're having...

**Comment by artivilla** [comment]
For some reason git and autojump work but aws and pyenv don't. Are you able to access aws in your path?

**Comment by caarlos0** [comment]
![image](https://user-images.githubusercontent.com/245435/54734380-cafbb700-4b7d-11e9-85a5-23ef6dca0da0.png)


seems like the functions are loaded yes
