### ISSUE TITLE
Vendor dependencies in the source distribution

### ISSUE THREAD

**Issue by equal-l2** [getantibody/antibody#286]
I'd like to submit the formula for this product to Homebrew, a package manager for macOS.  
  
The problem is that Homebrew forbids downloading dependencies during the build time. In order to circumvent this rule, dependencies must be vendored in the source distribution.

**Comment by caarlos0** [comment]
goreleaser is structured in the same way and have a formula on homebrew

https://github.com/Homebrew/homebrew-core/blob/master/Formula/goreleaser.rb

I have no intention in vendoring the deps inside the repo though.

**Comment by equal-l2** [comment]
Sorry, I meant I want to submit the formula to **homebrew-core**.

**Comment by caarlos0** [comment]
goreleaser is also on homebrew core, see link above...

**Comment by equal-l2** [comment]
I'm sorry but I don't understand how goreleaser is involved in my problem.  

I want to add new formula for antibody to homebrew-core, and in order to achieve this, dependencies must be included in the source archive file (tar.gz or zip).

I understand that you don't want to vendor dependencies in the repo.
Is it possible for you to prepare another archive which contains vendor dependencies, when releasing?

**Comment by caarlos0** [comment]
my point is that goreleaser also don't have deps vendored and has a formula on homebrew-core.

this means I don't need to vendor my deps - also this project uses go modules, so if you run `go build` or whatever with go 1.11+ it will already handle the deps, which I think is what happens on goreleaser core formula.

this also implies that antibody build never has a 'vendor' folder...

**Comment by equal-l2** [comment]
I get your point now, I have about misunderstood Homebrew's policy maybe...
Thank you for the detailed explanation!

**Comment by caarlos0** [comment]
no problem :) 

thanks
