### ISSUE TITLE
Kind: bash?

### ISSUE THREAD

**Issue by borekb** [getantibody/antibody#287]
I'm trying to use [these Yarn completions](https://github.com/dsifford/yarn-completion) for Bash in zsh (via `bashcompinit`). Would something like this be possible?

```
antibody bundle dsifford/yarn-completion kind:bash
```

**Comment by borekb** [comment]
Sorry, missed `path:...`, this can easily be achieved as

```
antibody bundle dsifford/yarn-completion path:yarn-completion.bash
```

Feel free to close :)

**Comment by caarlos0** [comment]
awesome!
