### ISSUE TITLE
Updating Plugins

### ISSUE THREAD

**Issue by jonleopard** [getantibody/antibody#288]
Hello!

First off, just wanted to say thanks for writing this great plugin manager. No issues to report here, I just have a quick question regarding plugin updates.

I've followed the guide on how to bundle the plugins into a bundles.sh file. Anytime I want to update my zsh plugins, do I need to re-bundle or can I just simply run `antibody update`? Here's my [antibody.zsh](https://github.com/jonleopard/dotfiles/blob/master/zsh/.zsh/antibody.zsh) file if it helps.

Sorry for the trivial question.

Thanks again!

**Comment by caarlos0** [comment]
Hi, thanks!

You can just run `antibody update`, it will update all bundles inside `antibody home` :)

**Comment by jonleopard** [comment]
Awesome, thanks for clearing that up for me.

Cheers
