### ISSUE TITLE
Add support for non-github repositories.

### ISSUE THREAD

**Issue by mitinarseny** [getantibody/antibody#290]
Hello!

I really love antibody for lots of reasons. Most for the speed. And I came across with some ideas that would be nice to add.

So, these are the ideas:
* download plugins not only from github, but other repositories too.
* download plugins with `wget` or `curl`
* load packages from local directories

It is really useful if you have to deal with some plugins that are hosted not on github. For example, [iTerm Shell Intergation](https://www.iterm2.com/documentation-shell-integration.html). The current solution is to add the [script](https://github.com/mitinarseny/dotfiles/blob/master/iTerm2/.iterm2_shell_integration.zsh) to your dotfiles repo and to have in your `.zsh_plugins.txt` something like this:
```bash
mitinarseny/dotfiles path:iTerm2/.iterm2_shell_integration.zsh
```
But it is not so handy and antibody download it to `$(antibody home)` and it leads to have two identical scripts in different locations. Of course, you can create a repository on github that contains only this script and put it in your `.zsh_plugins.txt` then. But this script is not your creature and it might be unfair and possibly illegal to do it.

**Comment by caarlos0** [comment]
> But it is not so handy and antibody download it to `$(antibody home)` and it leads to have two identical scripts in different locations.

this is weird... shouldn't happen... will verify when I have some time

thanks for the report though
