### ISSUE TITLE
Antibody Not Installing to Correct Location

### ISSUE THREAD

**Issue by Mario253** [getantibody/antibody#292]
I know this is really minor, but installing antibody with the curl command now installs it to ./bin/antibody instead of /usr/local/bin/antibody, requiring a cd to /usr/local for the install to work as described. [The website](http://getantibody.github.io/install) describes it as installing to /usr/local/bin, meaning that some who are installing for the first time might not know where it ended up.

**Comment by caarlos0** [comment]
fixed docs, thanks for reporting!
