### ISSUE TITLE
Permission Issue with install script 

### ISSUE THREAD

**Issue by TheGinger** [getantibody/antibody#293]
Hi, I was recently setting up antibody on my raspberry pi and found that the install script was failing.
```
pi@raspberrypi:~ $ curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
getantibody/antibody info checking GitHub for latest tag
getantibody/antibody info found version: 4.1.2 for v4.1.2/Linux/armv7
install: cannot create regular file '/usr/local/bin/antibody': Permission denied
```
I was able to fix this by altering the one liner.
`curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin `

**Comment by caarlos0** [comment]
yeah seems like your used didn't had permissions to write to usr/local/bin, so sudo is a good way to fix it :)

the script will not ask for sudo because it looks shady, better to let the user decide 

will close the issue but feel free to add additional comments if you have any :)

**Comment by charitarthchugh** [comment]
A suggestion - putting the script in the home directory of the user, if it is possible. 
Maybe `~/bin` or `~/.local/bin`
