### ISSUE TITLE
Thought process behind cache folder naming?

### ISSUE THREAD

**Issue by jesseleite** [getantibody/antibody#309]
I realize antibody doesn't (and won't) do anything for specific frameworks or plugins.  I do agree with that philosophy, but if I bundle oh-my-zsh:

```
antibody bundle robbyrussell/oh-my-zsh
```

I'm required to:

```
export ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
```

And I'm wondering why this couldn't be something as clean as:

```
export ZSH="$(antibody home)/robbyrussell/oh-my-zsh"
```

That said, I'm curious what the thought process behind cache folder naming was?  Thoughts?

**Comment by caarlos0** [comment]
Hey

you can load specific plugins like `robbyrussell/oh-my-zsh path:plugins/asdf` - its a bit repetitive but should work.

about the folder naming, is to ensure it won't conflict with other sources (e.g. gitlab, etc). The convention is the same as antigen.

**Comment by jesseleite** [comment]
Hey @caarlos0 already loading plugins via `path:`, and it works well 👌  My comment was about having to reference such a long path string when setting `ZSH` in that example.

What if there was an `antibody path` command that could the absolute path of a specific bundle?  Then we could:
```
export ZSH="$(antibody path robbyrussell/oh-my-zsh)"
```

Instead of:
```
export ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
```

I think a command like this could compliment your `antibody home` and `antibody list` commands.  Thoughts on this?

**Comment by caarlos0** [comment]
that I think makes sense yeah...
