### ISSUE TITLE
antibody path command

### ISSUE THREAD

**Issue by caarlos0** [getantibody/antibody#310]
Hey @caarlos0 already loading plugins via `path:`, and it works well 👌  My comment was about having to reference such a long path string when setting `ZSH` in that example.

What if there was an `antibody path` command that could the absolute path of a specific bundle?  Then we could:
```
export ZSH="$(antibody path robbyrussell/oh-my-zsh)"
```

Instead of:
```
export ZSH="$(antibody home)/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
```

I think a command like this could compliment your `antibody home` and `antibody list` commands.  Thoughts on this?

_Originally posted by @jesseleite in https://github.com/getantibody/antibody/issues/309#issuecomment-539604408_

**Comment by jesseleite** [comment]
I guess this can be closed.  Thanks again man ❤️

**Comment by caarlos0** [comment]
thanks for the PRs :)
