### ISSUE TITLE
Static loading from local path?

### ISSUE THREAD

**Issue by jesseleite** [getantibody/antibody#311]
Is it possible to static load a local path?  For example, this works in my `.zshrc`:

```
source <(antibody init)

antibody bundle ~/.dotfiles/zsh/an-old-hope.zsh-theme
```

But this does not work in my plugins.txt file:

```
~/.dotfiles/zsh/an-old-hope.zsh-theme
```

Am I doing something wrong, or does the plugins.txt file only work with repository based bundles?

**Comment by caarlos0** [comment]
for local paths the path needs to start with `/`... maybe we could change that to include `~` as well, as it is pretty common...

**Comment by jesseleite** [comment]
Cool, I might mess with PR's for these two new issues I've brought up for Hacktoberfest, if that's okay.  Not sure how far I'll get though, as I've never programmed in Go before 🙈

**Comment by caarlos0** [comment]
Feel free to :) Happy to comment on them and help you get through any issues 🚀

**Comment by jesseleite** [comment]
Cool thanks, appreciate it 😊

**Comment by jesseleite** [comment]
I guess this can be closed. Thanks again man ❤️
