### ISSUE TITLE
Support for asking SSH passphrases

### ISSUE THREAD

**Issue by jamezrin** [getantibody/antibody#325]
Similar to #190 

After updating the file that contains the plugins, it hangs because it tries to clone plugins through ssh and my ssh key has a passphrase, and instead of asking it, it just hangs.

My ssh agent is working as expected, but at the time antibody loads the bundle, I might have not provided the password to the ssh agent already, resulting in this hang.

I don't know if by default antibody clones through HTTPS or SSH, but in my system it is forced to SSH because in the .gitconfig file I have this
```
 # Enforce SSH
 [url "git@github.com:"]
     insteadOf = https://github.com/
```

**Comment by jamezrin** [comment]
Using gnome-keyring makes this not an issue, since it doesn't prompt in the CLI and instead asks through a GUI.

**Comment by caarlos0** [comment]
antibody closes with HTTPS, will see how to make it fail fast and maybe even ignore those configs

also, you can make a static bundle of your plugins so you don't need to call antibody on every shell... 

example https://github.com/caarlos0/dotfiles/blob/master/antibody/install.sh#L8
