### ISSUE TITLE
Command not found: compdef error

### ISSUE THREAD

**Issue by scutulatium** [getantibody/antibody#327]
Hi,

I'm trying to make antibody load plenty of plugins statically without success.  When I open a terminal, each plugin appears to complain that the compdef command was not found.  Any ideas that might help?

Thanks,

**Comment by jamezrin** [comment]
What do you have on your zshrc file? You have to load compinit

**Comment by caarlos0** [comment]
as @jamezrin pointed out, you need to load `compinit`, check an example https://github.com/caarlos0/dotfiles/blob/e67930e9b1f4153e4340a468c7bbb373946ec28b/zsh/zshrc.symlink#L32-L36

if it still doesn't work, it might be something on the particular plugin you're trying to load.

hope you figure it out :)
