### ISSUE TITLE
Version 5.0 breaks with repositories accessed via SSH

### ISSUE THREAD

**Issue by jshiell** [getantibody/antibody#344]
Since updating to version 5.0 (and 5.0.1) updates on repositories access by SSH seem to be broken. While this can be avoided for public repos by switching to SSH, I also have a private set of extensions for my employer which does contain some internal setup that cannot be public, which necessitates key authentication.

As an reproducible example with a public repo:
```
$ antibody bundle git@github.com:jshiell/infernus-zsh-theme.git
antibody: git clone failed for git@github.com:jshiell/infernus-zsh-theme.git
antibody: error: failed to bundle: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Needless to say, my public key setup is fine:
```
$ ssh git@github.com

PTY allocation request failed
Hi jshiell! You've successfully authenticated, but GitHub does not provide shell access.
Shared connection to github.com closed.
```

And this exact setup worked perfectly with 4.x.

I suspect it's related to the move to go-git, but I fear I've no further insight to add.

And, of course, thanks for all you fine work on antibody! It's much appreciated.

**Comment by caarlos0** [comment]
hey

if you run `ssh-add` first, does it work?

**Comment by jshiell** [comment]
Good idea, and yes, that resolves the issue.

```
$ antibody bundle git@github.com:jshiell/infernus-zsh-theme.git
antibody: git clone failed for git@github.com:jshiell/infernus-zsh-theme.git
antibody: error: failed to bundle: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

$ ssh-add
Identity added: /Users/jshiell/.ssh/id_rsa (/Users/jshiell/.ssh/id_rsa)

$ antibody bundle git@github.com:jshiell/infernus-zsh-theme.git
source /Users/jshiell/Library/Caches/antibody/git-AT-github.com-COLON-jshiell-SLASH-infernus-zsh-theme.git/infernus.zsh
fpath+=( /Users/jshiell/Library/Caches/antibody/git-AT-github.com-COLON-jshiell-SLASH-infernus-zsh-theme.git )
```

Thanks very much!

**Comment by caarlos0** [comment]
btw, if the repo is public, you can just use https which would lead to less problems...

**Comment by jshiell** [comment]
Noted - it’s actually a private repo, that caused the problem; this was just a convenient example to reproduce the problem on 😄
