### ISSUE TITLE
Slow boot times after setting up

### ISSUE THREAD

**Issue by joshghent** [getantibody/antibody#351]
Hi there, first off, great project! Can't wait to use!

Had a few issues though, I had a lot of `command not found` issues like #249 
I resolved it using the fix stated but this lead my terminal start times to rise to 3 seconds (up from 0.3 seconds when I was using antigen)

I have a similar setup as described in #249, can you please point me in the right direction?

**Comment by caarlos0** [comment]
Hey! 

So, you are sourcing a `~/.zsh_plugins.sh` file directly, right?

So its probably some of the plugins... you can try commenting them out and testing...

Maybe this helps as well: https://carlosbecker.com/posts/speeding-up-zsh

**Comment by joshghent** [comment]
Hey @caarlos0 - yeah I was but yeah it was probably an issue with plugins. I discovered the project through that blog post! 👍 I'll close this issue now but cheers for your help.
