### ISSUE TITLE
Support zplugin/zsh-defer?

### ISSUE THREAD

**Issue by tmpm697** [getantibody/antibody#357]
I want to use zsh-defer or zinit turbo mode that requires to decorate `source` command in `zsh_plugins.sh` like:
```
zsh-defer source <...>
```
Can you give flag that support this feature? like:
```
zsh-users/zsh-autosuggestions kind:zsh path:zsh-autosuggestions.zsh zsh-defer:yes
```

**Comment by caarlos0** [comment]
rather not.

if you use static loading, you can get this already with some hack:

```
antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
antibody bundle < ~/.defer_zsh_plugins.txt | sed 's/source/zsh-defer/g' >> ~/.zsh_plugins.sh
```
