### ISSUE TITLE
Static loading produces empty file

### ISSUE THREAD

**Issue by marlonrichert** [getantibody/antibody#361]
I followed the instructions at https://getantibody.github.io/usage/#static-loading, but all it gives me is an empty `~/zsh_plugins.sh` file.

# Steps to Reproduce
1. Create a file `~/.zsh_plugins.txt`.
1. Put the string `marlonrichert/zsh-autocomplete` in that file.
1. Run the following on the command line:
   ```sh
   source <(antibody init)
   antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
   ```
1. Look at what's inside `~/.zsh_plugins.sh`.

# Actual Result
`~/.zsh_plugins.sh` is **empty**.

# Expected Result
I should be able to source `~/.zsh_plugins.sh` in order to run `marlonrichert/zsh-autocomplete`.

# Additional Notes
If I use dynamic loading
```sh
source <(antibody init)
antibody bundle < ~/.zsh_plugins.txt
```
in my `~/.zshrc`, that works just fine.

**Comment by andrewcrook** [comment]
@marlonrichert 

Looking through the docs

`source <(antibody init)`

in .zshrc is for Dynamic loading not Static loading .

> Note that in this case, **we should not put antibody init on our ~/.zshrc**. If you did that already, remove it from your ~/.zshrc and start a fresh terminal session.

[Antibody Docs](https://getantibody.github.io/usage/)

**Comment by caarlos0** [comment]
if you want to do static loading, you shouldn't run `source <(antibody init)`... that's probably the issue.

**Comment by borekb** [comment]
In my case, my mistake was that I removed `source <(antibody init)` from `.zshrc` and ran `source ~/.zshrc` – I was also seeing empty `.zsh_plugins.sh` after that.

The "start a fresh terminal session" in the docs is important. After doing so, everything worked fine.
