### ISSUE TITLE
Termux installation borked

### ISSUE THREAD

**Issue by alephalpha0** [getantibody/antibody#365]
I've been trying to get antibody going on the Android app Termux and so far no luck. When initializing with the version I got from `pkg install antibody` I've gotten several errors.  
1. The first is when I put `source<(antibody init)` in my `.zshrc` and load the shell, `/data/data/com.termux/files/home/.config/zsh/.zshrc:5: no such file or directory: source/proc/self/fd/12` is the first thing I see on the terminal.

2. When I run `% antibody init > antibnit.sh` and then:

    ```
   % sh antibinit.sh 
   antibinit.sh: 5: Syntax error: "(" unexpected
    ```
    is the outcome. 
3. Lastly.. when I run different variants of the `source<(antibody init)` I get various failures in stdout..
  1. `% source < (antibody init)` gives me `zsh: number expected`
  2. `% source < $(antibody init)` will output `zsh: no such file or directory: #!/usr/bin/env`
  3. `% source<(antibody init)` spits this out `zsh: no such file or directory: source/proc/self/fd/11` 

🥺 What is there to do?

**Comment by alephalpha0** [comment]
Forgot to add this too..

When I run `% curl -sfL git.io/antibody | sh -s - -b /usr/local/bin` I get 
```
getantibody/antibody info checking GitHub for latest tag
getantibody/antibody info found version: 6.1.0 for v6.1.0/Linux/arm64
install: cannot create directory ‘/usr’: Read-only file system
```

`% uname -m` outputs `aarch64`

**Comment by caarlos0** [comment]
seems to be something on termux, not on antibody.

I don't have anything with android to test it, so I cant help.

You can try to use static loading instead of dynamic, might work around those issues.
