### ISSUE TITLE
Antibody wrongly assumes the default branch for a repo is named "master"

### ISSUE THREAD

**Issue by mattmc3** [getantibody/antibody#369]
[As of October 1st](https://github.com/github/renaming#on-october-1-2020-newly-created-repositories-will-default-to-main) new repos created on GitHub will have their default branch [named "main" instead of "master"](https://github.com/github/renaming). Antibody assumes that "master" is the default branch and fails if a "master" branch doesn't exist.

This change won't apply to existing repos, leaving two different default branch names (not to mention other projects that already don't use master and default to "develop" or something else). Now, I know Antibody supports the `branch:main` syntax to specify a branch, but honestly that should not be necessary. I would suggest that Antibody should not assume a default branch name at all if one is not specifically provided and just simply omit the "-b" parameter when cloning. The Version variable in the struct should just stay nil. 
https://github.com/getantibody/antibody/blob/0632d068e35a736a83178dd523ee8dfd33c3e3fe/project/git.go#L97

I'd be happy to help with a PR to implement this. We're about a month away from it becoming an issue.

**Comment by caarlos0** [comment]
Nice catch! 

Yes, feel free to open a pr 🙏

Thanks :)

**Comment by caarlos0** [comment]
merged!

thanks @mattmc3 🚀
