### ISSUE TITLE
Add a "kind:clone" option to manage a clone-only repo

### ISSUE THREAD

**Issue by mattmc3** [getantibody/antibody#371]
Coming from the [zgen](https://github.com/tarjoilija/zgen) plugin manager, there's a "clone" option that doesn't do anything other than clones a repo. Obviously, you could just `git clone` yourself, but letting your shell's plugin manager do this allows you to then use it manage ongoing updates to that repo alongside all your other traditional shell plugins. You use this clone-only option when you to do something outside of the normal $PATH/$fpath/source options. An example might be that you want to clone and symlink the [iTerm2 themes](https://github.com/mbadolato/iTerm2-Color-Schemes), or maybe you want to use antibody to manage your oh-my-zsh or Prezto external plugins in your $ZSH_CUSTOM.

I think a simple way to add this to antibody would be to add another "kind" option beyond "zsh/path/fpath" - let's call it "kind:clone". If this is a feature you'd accept, I'd happily submit a PR that also included updates to the documentation.

**Comment by mattmc3** [comment]
After looking at the source, the undocumented "kind:dummy" appears to do this already. This seems like a useful feature to rename "clone" (or something more informative than "dummy") and add to the documentation, but as far as functionality I guess it's already there so maybe it's a non-issue. ¯\_(ツ)_/¯

**Comment by mattmc3** [comment]
PR submitted: https://github.com/getantibody/antibody/pull/372

**Comment by caarlos0** [comment]
Thanks @mattmc3! 🚀
