### ISSUE TITLE
Antibody not loading some plugins and showing weird behaviour?

### ISSUE THREAD

**Issue by dominikheinz** [getantibody/antibody#378]
Hi,
I am new to the antibody plugin manager (originally coming from ohmyzsh). Now I am trying to configure antibody to my needs.
With ohmyzsh I had various plugins installed. I tried to install the same ones with antibody and I noticed some weird behaviour / problems where some plugins wont load.

This is my zshrc:
```
# Setup environment variables
export EDITOR=nano
export HISTFILE=$HOME/.config/zsh/.zhistory

# Setup aliases
alias ll="ls -lha"

# Source antibody
source <(antibody init)

# Configure prompt colors and compinit
autoload -U colors && colors
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C
setopt promptsubst

# Load plugins
antibody bundle < $HOME/.config/zsh/.zsh_plugins
```

This is my zsh_plugins:
```
# Plugin
ohmyzsh/ohmyzsh path:plugins/sudo
ohmyzsh/ohmyzsh path:plugins/git
ohmyzsh/ohmyzsh path:plugins/pip
ohmyzsh/ohmyzsh path:plugins/history-substring-search
zsh-users/zsh-autosuggestions
zsh-users/zsh-completions

# Themes (todo)
```

The issues:

1. Running `antibody list` only shows 3 plugins being loaded, despite 6 being configured in the zsh_plugins:
```
https://github.com/ohmyzsh/ohmyzsh                  /home/void/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-ohmyzsh-SLASH-ohmyzsh
https://github.com/zsh-users/zsh-autosuggestions    /home/void/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions
https://github.com/zsh-users/zsh-completions        /home/void/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions
```

2. The _history-substring-search_ plugin for example is neither listed in `antibody list` and neither does it work
3. The _sudo_ is not listed in `antibody list` but it works just fine.

Why is that? Why are not all plugins loaded ? Why are some not showing as loaded but work.

There is a good chance that its just a user problem, as I am not very experienced with antibody. Can someone tell me what I am missing here, or is this an actual bug.

**Comment by cjonesy** [comment]
I am also experiencing the exact same issue.

**Comment by caarlos0** [comment]
oh-my-zsh plugins all show as a single plugin because its the same repository... 

can you run `antibody bundle < plugins` and paste the output (without running `antibody init` first)?

**Comment by cjonesy** [comment]
I had uninstalled antibody when I couldn't get it to work before, and when I re-installed to run this command it was suddenly working.

I'm not sure what I had done wrong, but in my case a reinstall fixed it.

**Comment by caarlos0** [comment]
This repo has been deprecated. Please check the notice in the README.

Thanks
