### ISSUE TITLE
Documentation confusion on path vs fpath

### ISSUE THREAD

**Issue by jrwrigh** [getantibody/antibody#379]
The current [documentation](https://getantibody.github.io/options/) regarding the differences between `kind:fpath` and `kind:path` is a bit confusing. Both state that they "just put the plugin folder in your `$PATH`. I'm guessing the difference is that `path` will try and find a file to source, while `fpath` won't?

**Comment by caarlos0** [comment]
This repo has been deprecated. Please check the notice in the README.

Thanks
