### ISSUE TITLE
getting an error when installing in FreeBSD

### ISSUE THREAD

**Issue by mrjayviper** [getantibody/antibody#381]
mypc% curl -sfL git.io/antibody | sh -s - -b /usr/local/bin

getantibody/antibody info checking GitHub for latest tag
getantibody/antibody info found version: 6.1.1 for v6.1.1/freebsd/x86_64
Invalid command '-dst'; type "help" for a list.

-----------

In saying that, I installed it yesterday using the same command (had to rebuilt the PC as i was testing some things) and it worked fine.

update: I installed git and retried the command and it worked this time. I'm guessing installing git installed some other command that can do the hash.

**Comment by caarlos0** [comment]
This repo has been deprecated. Please check the notice in the README.

Thanks
