### ISSUE TITLE
Add support for Darwin ARM64

### ISSUE THREAD

**Issue by shepherdjerred** [getantibody/antibody#382]
It'd be nice to be able to use antibody on new devices shipped with the Apple M1 processor, such as the 2020 Mac Mini, MacBook Air, and MacBook Pro 13''.

Can support be added for ARM64 Darwin?

**Comment by caarlos0** [comment]
Will need to wait for go 1.16...

**Comment by caarlos0** [comment]
This repo has been deprecated. Please check the notice in the README.

Thanks
