### ISSUE TITLE
Support for msys2 zsh

### ISSUE THREAD

**Issue by alexsarmiento** [getantibody/antibody#383]
When antibody is compiled  for Windows, golan automatically converts the file path separators to backslashes "\\" . "filepath.Join()".  But zsh is only available for windows under MSYS2  which handles the file paths with a unix style forward slashes  file separator "/".

```
antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
source C:\Users\kolan\AppData\Local\antibody\https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions\zsh-completions.plugin.zsh
fpath+=( C:\Users\kolan\AppData\Local\antibody\https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions )
```

When a new zsh session is started this is the error  I get:

`/c/Users/kolan/.zsh_plugins.sh:source:1: no such file or directory: C:UserskolaniAppDataLocalantibodyhttps-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completionszsh-completions.plugin.zsh`

That is, zsh won't understand the back slashes as file separators, (but it will understand c:/  ). A workaround would be to issue a command like this  instead .

`antibody bundle < ~/.zsh_plugins.txt| sed 's/\\/\//g' > ~/.zsh_plugins.sh`

My suggestion is to make antibody handle unix style paths only since zsh works as such even when is running on Windows.

**Comment by caarlos0** [comment]
This repo has been deprecated. Please check the notice in the README.

Thanks
