### ISSUE TITLE
antibody: git clone failed for https://github.com/zdharma/fast-syntax-highlighting Cloning into '/Users/user/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zdharma-SLASH-fast-syntax-highlighting'...

### ISSUE THREAD

**Issue by vnatarov-logz** [getantibody/antibody#390]
When opening iTerm terminal, got the next issue: `antibody: git clone failed for https://github.com/zdharma/fast-syntax-highlighting Cloning into '/Users/user/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zdharma-SLASH-fast-syntax-highlighting'...`

Solution is:
```
mkdir -p /Users/$(whoami)/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zdharma-SLASH-fast-syntax-highlighting
```

Please fix the same action in the code.
Thanks

**Comment by nega0** [comment]
The problem is https://github.com/zdharma/fast-syntax-highlighting 404's now. @zdharma deleted their Github account. Try using https://github.com/zdharma-continuum/fast-syntax-highlighting and everything should work fine.
